server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/v1/books/**

            - id: author-service
              uri: lb://AUTHOR-SERVICE
              predicates:
                - Path=/api/v1/authors/**

            - id: loan-service
              uri: lb://LOAN-SERVICE
              predicates:
                - Path=/api/v1/loans/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  jwt:
    secret: "this-is-a-very-long-secret-key-for-dev-only-123456789"